name: Crawler

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@master
    with:
      override-files: |
        https://raw.githubusercontent.com/ietf-ribose/bibxml-service/update-lockfile/Gemfile=Gemfile
        https://raw.githubusercontent.com/ietf-ribose/bibxml-service/update-lockfile/Gemfile.lock=Gemfile.lock
      args: ${{ github.event.inputs.args }}
      commit-indexes: false
