name: Generate Lockfile

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  
jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - run: bundle install
      - run: |
          git add Gemfile.lock
          git config user.name github-actions
          git config user.email github-actions@github.com

          git diff --quiet && git diff --staged --quiet || (git commit -m 'add lockfile' && git push)
